// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AniEmpty: typeof import('./../components/empty/AniEmpty.vue')['default']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    BaseOption: typeof import('./../components/editor/components/BaseOption.vue')['default']
    BreadCrumb: typeof import('./../components/breadcrumb/bread-crumb.vue')['default']
    BreadPage: typeof import('./../components/breadcrumb/bread-page.vue')['default']
    ColorPicker: typeof import('./../components/editor/components/ColorPicker.vue')['default']
    DragResizer: typeof import('./../components/editor/components/DragResizer.vue')['default']
    Editor: typeof import('./../components/editor/components/Editor.vue')['default']
    EditorPreview: typeof import('./../components/editor/components/EditorPreview.vue')['default']
    ImagePicker: typeof import('./../components/editor/components/ImagePicker.vue')['default']
    InputColor: typeof import('./../components/editor/components/InputColor.vue')['default']
    InputImage: typeof import('./../components/editor/components/InputImage.vue')['default']
    InputTexter: typeof import('./../components/editor/components/InputTexter.vue')['default']
    Marquee: typeof import('./../components/editor/blocks/text/marquee.vue')['default']
    Option: typeof import('./../components/editor/blocks/date/option.vue')['default']
    Page403: typeof import('./../components/error/page-403.vue')['default']
    PanelHeader: typeof import('./../components/editor/components/PanelHeader.vue')['default']
    PanelLeft: typeof import('./../components/editor/components/PanelLeft.vue')['default']
    PanelMain: typeof import('./../components/editor/components/PanelMain.vue')['default']
    PanelMainBlock: typeof import('./../components/editor/components/PanelMainBlock.vue')['default']
    PanelMainHeader: typeof import('./../components/editor/components/PanelMainHeader.vue')['default']
    PanelRight: typeof import('./../components/editor/components/PanelRight.vue')['default']
    Render: typeof import('./../components/editor/blocks/date/render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Temp.dev1': typeof import('./../components/breadcrumb/temp.dev1.vue')['default']
    Toast: typeof import('./../components/toast/toast.vue')['default']
  }
}
