/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_app': RouteRecordInfo<'/_app', '/_app', Record<never, never>, Record<never, never>>,
    '/content': RouteRecordInfo<'/content', '/content', Record<never, never>, Record<never, never>>,
    '/content/category': RouteRecordInfo<'/content/category', '/content/category', Record<never, never>, Record<never, never>>,
    '/content/comment': RouteRecordInfo<'/content/comment', '/content/comment', Record<never, never>, Record<never, never>>,
    '/content/material-category': RouteRecordInfo<'/content/material-category', '/content/material-category', Record<never, never>, Record<never, never>>,
    '/content/post': RouteRecordInfo<'/content/post', '/content/post', Record<never, never>, Record<never, never>>,
    '/dev/nav': RouteRecordInfo<'/dev/nav', '/dev/nav', Record<never, never>, Record<never, never>>,
    '/dev/openapi': RouteRecordInfo<'/dev/openapi', '/dev/openapi', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/log': RouteRecordInfo<'/log', '/log', Record<never, never>, Record<never, never>>,
    '/log/auth': RouteRecordInfo<'/log/auth', '/log/auth', Record<never, never>, Record<never, never>>,
    '/log/operation': RouteRecordInfo<'/log/operation', '/log/operation', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
    '/setting/common': RouteRecordInfo<'/setting/common', '/setting/common', Record<never, never>, Record<never, never>>,
    '/setting/function': RouteRecordInfo<'/setting/function', '/setting/function', Record<never, never>, Record<never, never>>,
    '/setting/mail': RouteRecordInfo<'/setting/mail', '/setting/mail', Record<never, never>, Record<never, never>>,
    '/system/department': RouteRecordInfo<'/system/department', '/system/department', Record<never, never>, Record<never, never>>,
    '/system/dict': RouteRecordInfo<'/system/dict', '/system/dict', Record<never, never>, Record<never, never>>,
    '/system/menu': RouteRecordInfo<'/system/menu', '/system/menu', Record<never, never>, Record<never, never>>,
    '/system/role': RouteRecordInfo<'/system/role', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/user': RouteRecordInfo<'/system/user', '/system/user', Record<never, never>, Record<never, never>>,
    '/_demo': RouteRecordInfo<'/_demo', '/_demo', Record<never, never>, Record<never, never>>,
    '/_login': RouteRecordInfo<'/_login', '/_login', Record<never, never>, Record<never, never>>,
  }
}
