// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdownButton: typeof import('@arco-design/web-vue')['DropdownButton']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Block: typeof import('./../components/editor/panel-main/components/block.vue')['default']
    BlockAttr: typeof import('./../components/editor/panel-right/block-attr.vue')['default']
    BreadCrumb: typeof import('./../components/breadcrumb/bread-crumb.vue')['default']
    BreadPage: typeof import('./../components/breadcrumb/bread-page.vue')['default']
    ColorPicker: typeof import('./../components/editor/components/ColorPicker.vue')['default']
    DragResizer: typeof import('./../components/editor/components/DragResizer.vue')['default']
    Editor: typeof import('./../components/editor/index.vue')['default']
    Header: typeof import('./../components/editor/panel-main/components/header.vue')['default']
    ImagePicker: typeof import('./../components/editor/components/ImagePicker.vue')['default']
    Option: typeof import('./../components/editor/items/text/option.vue')['default']
    Page403: typeof import('./../components/error/page-403.vue')['default']
    PanelHeader: typeof import('./../components/editor/panel-header/index.vue')['default']
    PanelLeft: typeof import('./../components/editor/panel-left/index.vue')['default']
    PanelMain: typeof import('./../components/editor/panel-main/index.vue')['default']
    PanelRight: typeof import('./../components/editor/panel-right/index.vue')['default']
    Render: typeof import('./../components/editor/items/text/render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextAttr: typeof import('./../components/editor/panel-right/text-attr.vue')['default']
    Toast: typeof import('./../components/toast/toast.vue')['default']
  }
}
