name: 自动部署

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 克隆代码
        uses: actions/checkout@v2

      - name: 设置环境
        uses: actions/setup-node@v2

      - name: 安装依赖
        run: npm install

      - name: 构建产物
        run: npm run build
      
      - name: 上传产物
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      - name: 部署分支
        id: deployment
        uses: actions/deploy-pages@v2 
