# 工作流名称，可自定义
name: 自动部署

# 事件监听，决定什么时候触发该工作流内的任务
on:
  # 在master分支推动到github时触发
  push:
    branches: [ master ]

# 任务集合，可包含多个任务
jobs:
  # 任务名称
  build:
    # 运行的操作系统
    runs-on: ubuntu-latest

    # 步骤集合，可包含多个步骤
    steps:
      # 单个步骤，没有名称，直接使用一个action
      - uses: actions/checkout@v2

      # 单个步骤，带有名称，带有参数
      - name: build and deploy
        run: |
          npm install
          npm run build
          cd dist
          git config --global user.name "juetan"
          git config --global user.email "810335188@qq.com"
          git init
          git add -A
          git commit -m "Build through github action"
          git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
